### ISSUE TITLE
ImportError: cannot import name Merge

### ISSUE THREAD

**Issue by yana-xuyan** [sterling239/audio-emotion-recognition#2]
I was trying to run your work, but I got an error as follows.

/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "code_yan_lstm.py", line 11, in <module>
    import models
  File "/opt/xuyan/tensorflow/audio-emotion-recognition-master/models.py", line 11, in <module>
    from keras.layers.core import Dense, Dropout, Activation, Merge, TimeDistributedDense
ImportError: cannot import name Merge

**Comment by sterling239** [comment]
Hi! 
This code was written in Keras 1.2, you probably have a newer version. To run this code you have to modify it corresponding to changes done in your version of Keras. For example, Merge layer was deprecated, moreover, it is not used in script code.py, you should remove it from import line. In addition, TimeDistributedDense layer was also deprecated, use TimeDistributed wrapper instead of old version

**Comment by yana-xuyan** [comment]
Thanks! Btw, what's the tensorflow version when you write this code? I installed Keras 1.2 instead, but is seems that tensorflow version should match keras version.

**Comment by sterling239** [comment]
You can try tf versions older than 2 years, like 0.8.0. I actually not guarantee that my code will work since that was very long time ago=) But the best way to reproduce my experiments is to code the same things one more time instead of copy-paste
